version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: job-portal-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: job-portal-server
    ports:
      - "5555:5555"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://job-portal-mongo:27017/job-portal
    restart: always

  client:
    build: ./client
    container_name: job-portal-client
    ports:
      - "5137:5137"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - server
    restart: always

volumes:
  mongo-data:
